<template>
  <section class="pt-10 pb-20 lg:px-24 px-4 flex justify-center items-center">
    <div
      class="bg-[#dd5e35] w-full lg:h-150 h-fit rounded-xl p-6 flex flex-col justify-center items-center text-white"
    >
      <p class="text-2xl font-great-vibes">Our Newsletter</p>
      <h1
        class="mt-3 lg:text-6xl text-5xl font-bebas-neue text-center max-w-xl font-bold"
      >
        COME FOR THE COFFEE, STAY FOR THE CREW. WE ARE YOUR DAILY HANGOUT SPOT.
      </h1>
      <p class="mt-3 text-center">
        Get 25% off on your first order just by subscribing to our newsletter
      </p>
      <div
        class="mt-5 bg-white px-7 py-3 rounded-xl flex lg:flex-row flex-col lg:gap-2 gap-5 items-center"
      >
        <input
          type="email"
          class="bg-transparent outline-none text-black"
          placeholder="Enter Email Address"
        />
        <button
          class="px-7 py-3 bg-[#f2bf4a] border-2 border-[#28543A] rounded-2xl shadow-[0px_4px_0px_#28543A] font-bold text-[#28543A] uppercase transition-all cursor-pointer hover:translate-y-[2px] hover:shadow-[2px_2px_0px_#28543A] active:scale-95"
        >
          SUBSCRIBE NOW
        </button>
      </div>
    </div>
  </section>
</template>
<script>
  export default {};
</script>
