<template>
  <main
    id="hero"
    class="min-h-screen overflow-hidden bg-[#17623b] pb-15 pt-32 flex flex-col justify-center items-center w-full"
  >
    <div class="grid lg:grid-cols-2 grid-cols-1 gap-15">
      <div
        class="w-full md:max-w-lg text-white px-4 lg:px-10 lg:order-1 order-2"
      >
        <div class="relative w-fit h-fit">
          <p
            class="lg:text-7xl md:text-6xl text-5xl tracking-wide font-bold font-bebas-neue"
          >
            START <span class="text-[#f2bf4a]">YOUR DAY</span> RIGHT WITH
            FRESHLY BREWED COFFEE
          </p>
        </div>
        <p class="mt-5 max-w-sm font-light">
          Start your day right with freshly brewed coffee made to energize your
          mornings and satisfy your senses.
        </p>
        <button
          class="px-7 mt-5 py-3 bg-[#dd5d36] border-2 border-gray-800 rounded-2xl shadow-[0px_4px_0px_#1f2937] font-bold text-white uppercase transition-all cursor-pointer hover:translate-y-[2px] hover:shadow-[2px_2px_0px_#28543A] active:scale-95"
        >
          SEE THE MENU
        </button>
        <div class="grid grid-cols-3 mt-10 gap-5 pb-5">
          <div
            class="md:w-full w-fit flex flex-col justify-center items-center border border-white/30 rounded-xl p-3"
          >
            <img src="assets/svg/coffee.svg" class="md:w-14 w-12" alt="" />
            <p class="font-bold text-center md:text-base text-sm max-w-[100px]">
              QUALITY FIRST
            </p>
          </div>
          <div
            class="md:w-full w-fit flex flex-col justify-center items-center border border-white/30 rounded-xl p-3"
          >
            <img
              src="assets/svg/coffee-beans.svg"
              class="md:w-14 w-12"
              alt=""
            />
            <p class="font-bold text-center md:text-base text-sm max-w-[100px]">
              QUALITY FIRST
            </p>
          </div>
          <div
            class="md:w-full w-fit flex flex-col justify-center items-center border border-white/30 rounded-xl p-3"
          >
            <img src="assets/svg/cup-coffee.svg" class="md:w-14 w-12" alt="" />
            <p class="font-bold text-center md:text-base text-sm max-w-[100px]">
              COFFEE COMMUNITY
            </p>
          </div>
        </div>
      </div>
      <div
        class="w-full relative flex justify-center lg:order-2 order-1 h-fit max-w-md mx-auto"
      >
        <div
          class="md:w-[400px] md:h-[400px] w-[250px] h-[250px] bg-white p-2 rounded-xl rotate-6"
        >
          <img
            src="assets/img/barista.webp"
            class="w-full h-full rounded-xl object-cover object-center"
            alt=""
          />
        </div>

        <div
          class="absolute lg:-bottom-25 -bottom-5 md:-left-15 left-10 lg:w-[300px] lg:h-[300px] md:w-[200px] md:h-[200px] w-[150px] h-[150px] bg-white p-2 rounded-xl -rotate-6 z-10"
        >
          <img
            src="assets/img/coffee-display.webp"
            class="w-full h-full rounded-xl object-cover object-bottom"
            alt=""
          />
        </div>
      </div>
    </div>
  </main>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 1200 80"
    preserveAspectRatio="none"
    class="-mt-1"
    style="display: block; width: 100%; height: 40px"
  >
    <path
      d="M0,0 H1200 V60 
         L1180,58 L1145,63 L1110,56 L1080,61 L1030,57 
         L995,62 L960,59 L915,63 L880,58 L835,62 
         L800,56 L765,61 L720,58 L685,63 L640,57 
         L600,62 L565,58 L525,61 L490,56 L445,63 
         L410,59 L365,62 L320,57 L285,61 L245,56 
         L210,63 L165,58 L130,62 L90,57 L50,61 
         L25,58 L0,62 Z"
      fill="#17623b"
    />
  </svg>
</template>
<script>
  export default {};
</script>
