<template>
  <section
    class="lg:px-14 px-4 flex justify-center overflow-hidden"
    id="products"
  >
    <div class="flex lg:w-fit w-full justify-center items-center flex-col mt-4">
      <div
        class="w-full flex lg:flex-row flex-col gap-5 lg:items-end justify-between"
      >
        <div>
          <p class="font-great-vibes md:text-2xl text-xl text-red-500">
            Coffe Category
          </p>
          <div
            class="font-bebas-neue lg:text-6xl md:text-5xl text-4xl text-[#17623b] font-bold mt-3"
          >
            <h1>OUR COFFEE,</h1>
            <h1>YOUR EXPERIENCE</h1>
          </div>
        </div>
        <button
          class="px-7 py-3 bg-[#17623b] border-2 border-[#28543A] rounded-2xl shadow-[0px_4px_0px_#28543A] font-bold text-white uppercase transition-all cursor-pointer hover:translate-y-[2px] hover:shadow-[2px_2px_0px_#28543A] active:scale-95"
        >
          OUR PRODUCTS
        </button>
      </div>
      <div
        class="grid lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 grid-cols-1 mt-10 gap-5 pb-20"
      >
        <div
          class="w-full p-6 h-full flex flex-col justify-center items-center rounded-xl bg-gray-200"
        >
          <img
            src="/assets/img/espresso.webp"
            class="lg:w-72 md:w-64 w-56"
            alt=""
          />
          <p class="text-5xl mt-5 text-[#17623b] text-center font-bebas-neue">
            ESPRESSO
          </p>
        </div>
        <div
          class="w-full p-6 h-full flex flex-col justify-center items-center rounded-xl bg-gray-200"
        >
          <img
            src="/assets/img/cappucino.webp"
            class="lg:w-72 md:w-64 w-56"
            alt=""
          />
          <p class="text-5xl mt-5 text-[#17623b] text-center font-bebas-neue">
            CAPPUCCINO
          </p>
        </div>
        <div
          class="w-full p-6 h-fit flex flex-col justify-center items-center rounded-xl bg-gray-200"
        >
          <img
            src="/assets/img/iced-coffee.webp"
            class="lg:w-72 md:w-64 w-56"
            alt=""
          />
          <p class="text-5xl mt-5 text-[#17623b] text-center font-bebas-neue">
            ICED COFFEE
          </p>
        </div>
        <div
          class="w-full p-6 h-full flex flex-col justify-center items-center rounded-xl bg-gray-200"
        >
          <img
            src="/assets/img/cold-brew.webp"
            class="lg:w-72 md:w-64 w-56"
            alt=""
          />
          <p class="text-5xl mt-5 text-[#17623b] text-center font-bebas-neue">
            COLD BREW
          </p>
        </div>
        <div
          class="w-full p-6 h-full flex flex-col justify-center items-center rounded-xl bg-gray-200"
        >
          <img
            src="/assets/img/macchiato.webp"
            class="lg:w-72 md:w-64 w-56"
            alt=""
          />
          <p class="text-5xl mt-5 text-[#17623b] text-center font-bebas-neue">
            MACCHIATO
          </p>
        </div>
        <div
          class="w-full p-6 h-full flex flex-col justify-center items-center rounded-xl bg-gray-200"
        >
          <img
            src="/assets/img/flat-white.webp"
            class="lg:w-72 md:w-64 w-56"
            alt=""
          />
          <p class="text-5xl mt-5 text-[#17623b] text-center font-bebas-neue">
            FLAT WHITE
          </p>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
  export default {};
</script>
